from __future__ import annotations

import json
import os
import re
import urllib.error
import urllib.request
from dataclasses import dataclass
from typing import Any


GENAI_ENDPOINT = os.getenv("GENAI_API_URL", "https://api.openai.com/v1/chat/completions")
GENAI_MODEL = os.getenv("GENAI_MODEL", "gpt-4o-mini")


@dataclass(frozen=True)
class GenAIPrediction:
    label: str
    confidence: float
    rationale: str
    source: str


def _prompt(subject: str, body: str) -> list[dict[str, str]]:
    return [
        {
            "role": "system",
            "content": (
                "Classify an email as important or normal. Important emails require "
                "timely action, affect money, security, legal/compliance, customers, "
                "incidents, access, deadlines, executives, or operations. Return only "
                "JSON with keys label, confidence, and rationale."
            ),
        },
        {
            "role": "user",
            "content": f"Subject: {subject.strip()}\n\nBody:\n{body.strip()}",
        },
    ]


def _parse_json_response(content: str) -> dict[str, Any]:
    try:
        return json.loads(content)
    except json.JSONDecodeError:
        match = re.search(r"\{.*\}", content, flags=re.DOTALL)
        if not match:
            raise
        return json.loads(match.group(0))


def _api_classify(subject: str, body: str) -> GenAIPrediction:
    api_key = os.getenv("OPENAI_API_KEY") or os.getenv("GENAI_API_KEY")
    if not api_key:
        raise RuntimeError("No GenAI API key configured")

    payload = {
        "model": GENAI_MODEL,
        "messages": _prompt(subject, body),
        "temperature": 0,
        "response_format": {"type": "json_object"},
    }
    request = urllib.request.Request(
        GENAI_ENDPOINT,
        data=json.dumps(payload).encode("utf-8"),
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        },
        method="POST",
    )

    with urllib.request.urlopen(request, timeout=20) as response:
        raw = json.loads(response.read().decode("utf-8"))

    content = raw["choices"][0]["message"]["content"]
    parsed = _parse_json_response(content)
    return GenAIPrediction(
        label=str(parsed.get("label", "normal")).strip().lower(),
        confidence=float(parsed.get("confidence", 0.0)),
        rationale=str(parsed.get("rationale", "Generated by configured GenAI provider.")),
        source="api",
    )


def _fallback_classify(subject: str, body: str) -> GenAIPrediction:
    text = f"{subject} {body}".lower()
    weighted_terms = {
        "urgent": 2,
        "immediate": 2,
        "today": 1,
        "deadline": 2,
        "blocked": 2,
        "outage": 3,
        "incident": 3,
        "security": 3,
        "legal": 3,
        "compliance": 3,
        "payroll": 2,
        "invoice": 2,
        "overdue": 2,
        "customer": 2,
        "client": 2,
        "approval": 1,
        "production": 3,
        "failed": 2,
        "breach": 3,
        "executive": 2,
        "ceo": 2,
        "access": 2,
    }
    score = sum(weight for term, weight in weighted_terms.items() if term in text)
    label = "important" if score >= 3 else "normal"
    confidence = min(0.55 + (score * 0.07), 0.95) if label == "important" else max(0.55, 0.9 - score * 0.08)
    rationale = (
        "Fallback reasoning found time-sensitive or risk-related signals."
        if label == "important"
        else "Fallback reasoning did not find strong urgency, risk, or deadline signals."
    )
    return GenAIPrediction(label=label, confidence=round(confidence, 2), rationale=rationale, source="fallback")


def classify_with_genai(subject: str, body: str) -> GenAIPrediction:
    try:
        return _api_classify(subject, body)
    except (RuntimeError, urllib.error.URLError, urllib.error.HTTPError, TimeoutError, KeyError, ValueError, json.JSONDecodeError) as exc:
        fallback = _fallback_classify(subject, body)
        return GenAIPrediction(
            label=fallback.label,
            confidence=fallback.confidence,
            rationale=f"{fallback.rationale} GenAI API unavailable: {exc}",
            source=fallback.source,
        )
